import os

SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')
SQLALCHEMY_DATABASE_URI_2 = os.environ.get('HEROKU_POSTGRESQL_MAUVE_URL')
SQLALCHEMY_DATABASE_URI_3 = os.environ.get('HEROKU_POSTGRESQL_ONYX_URL')
SQLALCHEMY_TRACK_MODIFICATIONS = False
